2022-12-18 02:19:49,382 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:20:20,029 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:20:20,074 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:20:20,074 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:20:20,075 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:20:20,075 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:20:20,134 INFO: [sanic.server] Starting worker [7016]
2022-12-18 02:20:20,134 INFO: [sanic.server] Starting worker [7016]
2022-12-18 02:20:28,964 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:20:28,964 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:20:28,967 INFO: [sanic.root] Server Stopped
2022-12-18 02:20:28,967 INFO: [sanic.root] Server Stopped
2022-12-18 02:20:28,980 INFO: [__main__] Closing down gracefully
2022-12-18 02:20:28,981 INFO: [sanic.server] Stopping worker [7016]
2022-12-18 02:20:28,981 INFO: [sanic.server] Stopping worker [7016]
2022-12-18 02:20:39,689 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:20:39,724 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:20:39,724 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:20:39,725 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:20:39,725 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:20:39,783 INFO: [sanic.server] Starting worker [7035]
2022-12-18 02:20:39,783 INFO: [sanic.server] Starting worker [7035]
2022-12-18 02:20:52,575 INFO: [__main__] Not found: /foows
2022-12-18 02:20:54,698 INFO: [__main__] Not found: /foows
2022-12-18 02:20:56,707 INFO: [__main__] Not found: /foows
2022-12-18 02:20:58,705 INFO: [__main__] Not found: /foows
2022-12-18 02:21:00,737 INFO: [__main__] Not found: /foows
2022-12-18 02:21:02,741 INFO: [__main__] Not found: /foows
2022-12-18 02:21:04,752 INFO: [__main__] Not found: /foows
2022-12-18 02:21:06,756 INFO: [__main__] Not found: /foows
2022-12-18 02:21:08,793 INFO: [__main__] Not found: /foows
2022-12-18 02:21:10,798 INFO: [__main__] Not found: /foows
2022-12-18 02:21:12,802 INFO: [__main__] Not found: /foows
2022-12-18 02:21:14,822 INFO: [__main__] Not found: /foows
2022-12-18 02:21:16,838 INFO: [__main__] Not found: /foows
2022-12-18 02:21:18,864 INFO: [__main__] Not found: /foows
2022-12-18 02:21:20,889 INFO: [__main__] Not found: /foows
2022-12-18 02:21:22,900 INFO: [__main__] Not found: /foows
2022-12-18 02:21:24,946 INFO: [__main__] Not found: /foows
2022-12-18 02:21:26,992 INFO: [__main__] Not found: /foows
2022-12-18 02:21:29,016 INFO: [__main__] Not found: /foows
2022-12-18 02:21:30,979 INFO: [__main__] Not found: /foows
2022-12-18 02:21:33,407 INFO: [__main__] Not found: /foows
2022-12-18 02:21:36,225 INFO: [__main__] Not found: /foows
2022-12-18 02:21:39,397 INFO: [__main__] Not found: /foows
2022-12-18 02:21:41,757 INFO: [__main__] Not found: /foows
2022-12-18 02:21:44,778 INFO: [__main__] Not found: /foows
2022-12-18 02:21:47,794 INFO: [__main__] Not found: /foows
2022-12-18 02:21:51,449 INFO: [__main__] Not found: /foows
2022-12-18 02:21:52,763 INFO: [__main__] Not found: /foows
2022-12-18 02:21:57,207 INFO: [__main__] Not found: /foows
2022-12-18 02:22:08,272 INFO: [__main__] Not found: /foows
2022-12-18 02:22:13,206 INFO: [__main__] Not found: /foows
2022-12-18 02:22:15,636 INFO: [__main__] Not found: /foows
2022-12-18 02:22:22,522 INFO: [__main__] Not found: /foows
2022-12-18 02:22:28,765 INFO: [__main__] Not found: /foows
2022-12-18 02:22:38,609 INFO: [sanic.root] connection open
2022-12-18 02:22:38,609 INFO: [sanic.root] connection open
2022-12-18 02:22:38,610 INFO: [__main__] New websocket client
2022-12-18 02:22:38,611 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:22:38,611 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:22:38,611 DEBUG: [entrance.ws_handler] Skipping unconfigured feature dare_app
2022-12-18 02:22:38,875 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:22:38,875 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:22:38,878 INFO: [sanic.root] Server Stopped
2022-12-18 02:22:38,878 INFO: [sanic.root] Server Stopped
2022-12-18 02:22:38,883 INFO: [__main__] Closing down gracefully
2022-12-18 02:22:38,884 INFO: [sanic.server] Stopping worker [7035]
2022-12-18 02:22:38,884 INFO: [sanic.server] Stopping worker [7035]
2022-12-18 02:22:38,885 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:22:39,491 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:22:39,523 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:22:39,523 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:22:39,524 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:22:39,524 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:22:39,581 INFO: [sanic.server] Starting worker [7051]
2022-12-18 02:22:39,581 INFO: [sanic.server] Starting worker [7051]
2022-12-18 02:22:40,138 INFO: [sanic.root] connection open
2022-12-18 02:22:40,138 INFO: [sanic.root] connection open
2022-12-18 02:22:40,139 INFO: [__main__] New websocket client
2022-12-18 02:22:40,139 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:22:40,140 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:22:40,140 DEBUG: [entrance.ws_handler] Skipping unconfigured feature dare_app
2022-12-18 02:22:49,876 DEBUG: [entrance.ws_handler] WS RECV: {'dares': ['d', 'b', 'b', 'b'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:22:49,877 WARNING: [entrance.ws_handler] Un-handleable request {'dares': ['d', 'b', 'b', 'b'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:22:49,877 DEBUG: [entrance.ws_handler] key = submit_dares||app||defaultTarget, request_map_optional = {}
2022-12-18 02:22:49,877 DEBUG: [entrance.ws_handler] WS SEND: {'channel': 'error', 'nfn_type': 'error', 'value': "Don't know how to handle request {'dares': ['d', 'b', 'b', 'b'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}"}
2022-12-18 02:30:39,833 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:30:40,190 INFO: [sanic.root] connection open
2022-12-18 02:30:40,190 INFO: [sanic.root] connection open
2022-12-18 02:30:40,191 INFO: [__main__] New websocket client
2022-12-18 02:30:40,192 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:30:40,192 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:30:40,192 DEBUG: [entrance.ws_handler] Skipping unconfigured feature dare_app
2022-12-18 02:30:44,006 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['h', 'h', 'h', 'h'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:30:44,006 WARNING: [entrance.ws_handler] Un-handleable request {'code': '', 'dares': ['h', 'h', 'h', 'h'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:30:44,006 DEBUG: [entrance.ws_handler] key = submit_dares||app||defaultTarget, request_map_optional = {}
2022-12-18 02:30:44,006 DEBUG: [entrance.ws_handler] WS SEND: {'channel': 'error', 'nfn_type': 'error', 'value': "Don't know how to handle request {'code': '', 'dares': ['h', 'h', 'h', 'h'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}"}
2022-12-18 02:31:04,685 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:31:04,685 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:31:04,688 INFO: [sanic.root] Server Stopped
2022-12-18 02:31:04,688 INFO: [sanic.root] Server Stopped
2022-12-18 02:31:04,693 INFO: [__main__] Closing down gracefully
2022-12-18 02:31:04,696 INFO: [sanic.server] Stopping worker [7051]
2022-12-18 02:31:04,696 INFO: [sanic.server] Stopping worker [7051]
2022-12-18 02:31:04,697 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:31:05,239 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:31:05,271 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:31:05,271 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:31:05,272 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:31:05,272 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:31:05,323 INFO: [sanic.server] Starting worker [7170]
2022-12-18 02:31:05,323 INFO: [sanic.server] Starting worker [7170]
2022-12-18 02:31:05,782 INFO: [sanic.root] connection open
2022-12-18 02:31:05,782 INFO: [sanic.root] connection open
2022-12-18 02:31:05,784 INFO: [__main__] New websocket client
2022-12-18 02:31:05,784 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:31:05,785 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:31:05,785 DEBUG: [entrance.ws_handler] Skipping unconfigured feature dare_app
2022-12-18 02:31:09,757 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:31:10,088 INFO: [sanic.root] connection open
2022-12-18 02:31:10,088 INFO: [sanic.root] connection open
2022-12-18 02:31:10,088 INFO: [__main__] New websocket client
2022-12-18 02:31:10,089 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:31:10,089 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:31:10,089 DEBUG: [entrance.ws_handler] Skipping unconfigured feature dare_app
2022-12-18 02:31:14,034 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:31:14,035 WARNING: [entrance.ws_handler] Un-handleable request {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:31:14,035 DEBUG: [entrance.ws_handler] key = submit_dares||app||defaultTarget, request_map_optional = {}
2022-12-18 02:31:14,036 DEBUG: [entrance.ws_handler] WS SEND: {'channel': 'error', 'nfn_type': 'error', 'value': "Don't know how to handle request {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}"}
2022-12-18 02:31:48,207 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:31:48,207 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:31:48,208 INFO: [sanic.root] Server Stopped
2022-12-18 02:31:48,208 INFO: [sanic.root] Server Stopped
2022-12-18 02:31:48,212 INFO: [__main__] Closing down gracefully
2022-12-18 02:31:48,213 INFO: [sanic.server] Stopping worker [7170]
2022-12-18 02:31:48,213 INFO: [sanic.server] Stopping worker [7170]
2022-12-18 02:31:48,213 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:31:48,873 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:31:48,909 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:31:48,909 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:31:48,910 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:31:48,910 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:31:48,964 INFO: [sanic.server] Starting worker [7185]
2022-12-18 02:31:48,964 INFO: [sanic.server] Starting worker [7185]
2022-12-18 02:31:49,116 INFO: [sanic.root] connection open
2022-12-18 02:31:49,116 INFO: [sanic.root] connection open
2022-12-18 02:31:49,117 INFO: [__main__] New websocket client
2022-12-18 02:31:49,118 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:31:49,118 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:31:49,118 DEBUG: [entrance.ws_handler] Skipping unconfigured feature dare_app
2022-12-18 02:31:52,675 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:31:53,018 INFO: [sanic.root] connection open
2022-12-18 02:31:53,018 INFO: [sanic.root] connection open
2022-12-18 02:31:53,019 INFO: [__main__] New websocket client
2022-12-18 02:31:53,019 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:31:53,019 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:31:53,020 DEBUG: [entrance.ws_handler] Skipping unconfigured feature dare_app
2022-12-18 02:31:55,805 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:31:55,805 WARNING: [entrance.ws_handler] Un-handleable request {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:31:55,805 DEBUG: [entrance.ws_handler] key = submit_dares||app||defaultTarget, request_map_optional = {}
2022-12-18 02:31:55,805 DEBUG: [entrance.ws_handler] WS SEND: {'channel': 'error', 'nfn_type': 'error', 'value': "Don't know how to handle request {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}"}
2022-12-18 02:34:13,669 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:34:13,669 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:34:13,671 INFO: [sanic.root] Server Stopped
2022-12-18 02:34:13,671 INFO: [sanic.root] Server Stopped
2022-12-18 02:34:13,675 INFO: [__main__] Closing down gracefully
2022-12-18 02:34:13,676 INFO: [sanic.server] Stopping worker [7185]
2022-12-18 02:34:13,676 INFO: [sanic.server] Stopping worker [7185]
2022-12-18 02:34:13,677 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:34:15,597 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:34:15,631 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:34:15,631 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:34:15,631 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:34:15,631 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:34:15,685 INFO: [sanic.root] connection open
2022-12-18 02:34:15,685 INFO: [sanic.root] connection open
2022-12-18 02:34:15,686 INFO: [__main__] New websocket client
2022-12-18 02:34:15,686 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:34:15,686 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:34:15,687 DEBUG: [entrance.ws_handler] Skipping unconfigured feature dare_app
2022-12-18 02:34:15,687 INFO: [sanic.server] Starting worker [7226]
2022-12-18 02:34:15,687 INFO: [sanic.server] Starting worker [7226]
2022-12-18 02:34:44,144 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:34:44,144 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:34:44,146 INFO: [sanic.root] Server Stopped
2022-12-18 02:34:44,146 INFO: [sanic.root] Server Stopped
2022-12-18 02:34:44,151 INFO: [__main__] Closing down gracefully
2022-12-18 02:34:44,152 INFO: [sanic.server] Stopping worker [7226]
2022-12-18 02:34:44,152 INFO: [sanic.server] Stopping worker [7226]
2022-12-18 02:34:44,153 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:34:44,751 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:34:44,765 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:34:44,765 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:34:44,766 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:34:44,766 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:34:44,817 INFO: [sanic.server] Starting worker [7241]
2022-12-18 02:34:44,817 INFO: [sanic.server] Starting worker [7241]
2022-12-18 02:34:45,109 INFO: [sanic.root] connection open
2022-12-18 02:34:45,109 INFO: [sanic.root] connection open
2022-12-18 02:34:45,110 INFO: [__main__] New websocket client
2022-12-18 02:34:45,110 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:34:45,110 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:34:45,111 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:35:05,967 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:35:05,968 ERROR: [sanic.error] Exception occurred while handling uri: 'ws://localhost:5000/ws'
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/websockets/impl.py", line 538, in recv
    raise asyncio.CancelledError()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 59, in handle_incoming_requests
    req = await asyncio.wait_for(self.ws.recv(), timeout=10*60)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 469, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/app.py", line 1003, in _websocket_handler
    await fut
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 91, in handle_ws
    await ws_handler.handle_incoming_requests()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 70, in handle_incoming_requests
    self._handle_websocket_closed()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 221, in _handle_websocket_closed
    feature.close()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 56, in close
    if self.id:
AttributeError: 'GameFeature' object has no attribute 'id'
2022-12-18 02:35:05,968 ERROR: [sanic.error] Exception occurred while handling uri: 'ws://localhost:5000/ws'
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/websockets/impl.py", line 538, in recv
    raise asyncio.CancelledError()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 59, in handle_incoming_requests
    req = await asyncio.wait_for(self.ws.recv(), timeout=10*60)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 469, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/app.py", line 1003, in _websocket_handler
    await fut
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 91, in handle_ws
    await ws_handler.handle_incoming_requests()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 70, in handle_incoming_requests
    self._handle_websocket_closed()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 221, in _handle_websocket_closed
    feature.close()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 56, in close
    if self.id:
AttributeError: 'GameFeature' object has no attribute 'id'
2022-12-18 02:35:06,305 INFO: [sanic.root] connection open
2022-12-18 02:35:06,305 INFO: [sanic.root] connection open
2022-12-18 02:35:06,306 INFO: [__main__] New websocket client
2022-12-18 02:35:06,306 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:35:06,306 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:35:06,306 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:35:09,119 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:35:09,120 CRITICAL: [entrance.feature.base] 
!!
!!
!! Feature dare_app trying to send disallowed notification None
!!
!!
2022-12-18 02:35:09,120 ERROR: [entrance.feature.base] Exception handling submit_dares(, ['j', 'j', 'j', 'j']) (see debug.log for details)
2022-12-18 02:35:09,128 DEBUG: [entrance.feature.base] Exception details
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 93, in handle
    result = await getattr(self, "do_" + req_type)(*args)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 50, in do_submit_dares
    return self._rpc_success()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 150, in _rpc_success
    return self._result(nfn_type=None, result=result, **kwargs)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 139, in _result
    self._check_nfn_type(nfn_type)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 124, in _check_nfn_type
    raise EntranceError(msg)
entrance.exceptions.EntranceError: Feature dare_app trying to send disallowed notification None
Stack (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 147, in <module>
    main(sys.argv[1:])
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 142, in main
    start(config)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 112, in start
    app.run(host=start_cfg["host"], port=start_cfg["port"])
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/mixins/startup.py", line 207, in run
    serve(primary=self)  # type: ignore
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/mixins/startup.py", line 851, in serve
    manager.run()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/manager.py", line 62, in run
    self.start()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/manager.py", line 70, in start
    process.start()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/process.py", line 58, in start
    self._process.start()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/serve.py", line 106, in worker_serve
    return _serve_http_1(
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/runners.py", line 272, in _serve_http_1
    _run_server_forever(
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/runners.py", line 153, in _run_server_forever
    loop.run_forever()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 91, in handle_ws
    await ws_handler.handle_incoming_requests()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 76, in handle_incoming_requests
    await self._handle_req(req)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 107, in _handle_req
    await feature.handle(request)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 99, in handle
    log.debug("Exception details", exc_info=True, stack_info=True)
2022-12-18 02:35:09,129 CRITICAL: [entrance.feature.base] 
!!
!!
!! Feature dare_app trying to send disallowed notification None
!!
!!
2022-12-18 02:35:09,129 ERROR: [entrance.ws_handler] Exception during _handle_req: Feature dare_app trying to send disallowed notification None (see debug.log for details)
2022-12-18 02:35:09,130 DEBUG: [entrance.ws_handler] _handle_req exception details
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 93, in handle
    result = await getattr(self, "do_" + req_type)(*args)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 50, in do_submit_dares
    return self._rpc_success()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 150, in _rpc_success
    return self._result(nfn_type=None, result=result, **kwargs)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 139, in _result
    self._check_nfn_type(nfn_type)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 124, in _check_nfn_type
    raise EntranceError(msg)
entrance.exceptions.EntranceError: Feature dare_app trying to send disallowed notification None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 76, in handle_incoming_requests
    await self._handle_req(req)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 107, in _handle_req
    await feature.handle(request)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 100, in handle
    result = self._rpc_failure(msg)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 157, in _rpc_failure
    return self._result(nfn_type=None, error=error, **kwargs)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 139, in _result
    self._check_nfn_type(nfn_type)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 124, in _check_nfn_type
    raise EntranceError(msg)
entrance.exceptions.EntranceError: Feature dare_app trying to send disallowed notification None
Stack (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 147, in <module>
    main(sys.argv[1:])
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 142, in main
    start(config)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 112, in start
    app.run(host=start_cfg["host"], port=start_cfg["port"])
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/mixins/startup.py", line 207, in run
    serve(primary=self)  # type: ignore
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/mixins/startup.py", line 851, in serve
    manager.run()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/manager.py", line 62, in run
    self.start()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/manager.py", line 70, in start
    process.start()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/process.py", line 58, in start
    self._process.start()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/serve.py", line 106, in worker_serve
    return _serve_http_1(
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/runners.py", line 272, in _serve_http_1
    _run_server_forever(
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/runners.py", line 153, in _run_server_forever
    loop.run_forever()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 91, in handle_ws
    await ws_handler.handle_incoming_requests()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 84, in handle_incoming_requests
    log.debug(
2022-12-18 02:35:09,131 DEBUG: [entrance.ws_handler] WS SEND: {'channel': 'error', 'nfn_type': 'error', 'value': 'Feature dare_app trying to send disallowed notification None'}
2022-12-18 02:42:11,271 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:42:11,271 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:42:11,273 INFO: [sanic.root] Server Stopped
2022-12-18 02:42:11,273 INFO: [sanic.root] Server Stopped
2022-12-18 02:42:11,278 INFO: [__main__] Closing down gracefully
2022-12-18 02:42:11,280 INFO: [sanic.server] Stopping worker [7241]
2022-12-18 02:42:11,280 INFO: [sanic.server] Stopping worker [7241]
2022-12-18 02:42:11,280 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:42:12,212 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:42:12,247 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:42:12,247 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:42:12,248 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:42:12,248 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:42:12,302 INFO: [sanic.server] Starting worker [7256]
2022-12-18 02:42:12,302 INFO: [sanic.server] Starting worker [7256]
2022-12-18 02:42:12,643 INFO: [sanic.root] connection open
2022-12-18 02:42:12,643 INFO: [sanic.root] connection open
2022-12-18 02:42:12,645 INFO: [__main__] New websocket client
2022-12-18 02:42:12,645 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:42:12,645 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:42:12,645 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:42:16,004 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:42:16,004 ERROR: [sanic.error] Exception occurred while handling uri: 'ws://localhost:5000/ws'
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/websockets/impl.py", line 538, in recv
    raise asyncio.CancelledError()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 59, in handle_incoming_requests
    req = await asyncio.wait_for(self.ws.recv(), timeout=10*60)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 469, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/app.py", line 1003, in _websocket_handler
    await fut
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 92, in handle_ws
    await ws_handler.handle_incoming_requests()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 70, in handle_incoming_requests
    self._handle_websocket_closed()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 221, in _handle_websocket_closed
    feature.close()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 57, in close
    if self.id:
AttributeError: 'GameFeature' object has no attribute 'id'
2022-12-18 02:42:16,004 ERROR: [sanic.error] Exception occurred while handling uri: 'ws://localhost:5000/ws'
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/websockets/impl.py", line 538, in recv
    raise asyncio.CancelledError()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 59, in handle_incoming_requests
    req = await asyncio.wait_for(self.ws.recv(), timeout=10*60)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 469, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/app.py", line 1003, in _websocket_handler
    await fut
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 92, in handle_ws
    await ws_handler.handle_incoming_requests()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 70, in handle_incoming_requests
    self._handle_websocket_closed()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 221, in _handle_websocket_closed
    feature.close()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 57, in close
    if self.id:
AttributeError: 'GameFeature' object has no attribute 'id'
2022-12-18 02:42:16,345 INFO: [sanic.root] connection open
2022-12-18 02:42:16,345 INFO: [sanic.root] connection open
2022-12-18 02:42:16,346 INFO: [__main__] New websocket client
2022-12-18 02:42:16,347 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:42:16,347 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:42:16,347 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:42:18,933 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:42:18,935 DEBUG: [entrance.ws_handler] WS SEND: {'result': '', 'nfn_type': 'submit_dares', 'channel': 'app', 'id': 1, 'target': 'defaultTarget'}
2022-12-18 02:49:04,382 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:49:04,382 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:49:04,384 INFO: [sanic.root] Server Stopped
2022-12-18 02:49:04,384 INFO: [sanic.root] Server Stopped
2022-12-18 02:49:04,389 INFO: [__main__] Closing down gracefully
2022-12-18 02:49:04,391 INFO: [sanic.server] Stopping worker [7256]
2022-12-18 02:49:04,391 INFO: [sanic.server] Stopping worker [7256]
2022-12-18 02:49:04,392 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:49:04,996 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:49:05,033 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:49:05,033 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:49:05,034 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:49:05,034 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:49:05,088 INFO: [sanic.server] Starting worker [7322]
2022-12-18 02:49:05,088 INFO: [sanic.server] Starting worker [7322]
2022-12-18 02:49:05,115 INFO: [sanic.root] connection open
2022-12-18 02:49:05,115 INFO: [sanic.root] connection open
2022-12-18 02:49:05,116 INFO: [__main__] New websocket client
2022-12-18 02:49:05,117 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:49:05,117 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:49:05,117 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:49:10,796 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:49:10,797 ERROR: [sanic.error] Exception occurred while handling uri: 'ws://localhost:5000/ws'
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/websockets/impl.py", line 538, in recv
    raise asyncio.CancelledError()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 59, in handle_incoming_requests
    req = await asyncio.wait_for(self.ws.recv(), timeout=10*60)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 469, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/app.py", line 1003, in _websocket_handler
    await fut
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 92, in handle_ws
    await ws_handler.handle_incoming_requests()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 70, in handle_incoming_requests
    self._handle_websocket_closed()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 221, in _handle_websocket_closed
    feature.close()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 57, in close
    if self.id:
AttributeError: 'GameFeature' object has no attribute 'id'
2022-12-18 02:49:10,797 ERROR: [sanic.error] Exception occurred while handling uri: 'ws://localhost:5000/ws'
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/websockets/impl.py", line 538, in recv
    raise asyncio.CancelledError()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 59, in handle_incoming_requests
    req = await asyncio.wait_for(self.ws.recv(), timeout=10*60)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 469, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/app.py", line 1003, in _websocket_handler
    await fut
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 92, in handle_ws
    await ws_handler.handle_incoming_requests()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 70, in handle_incoming_requests
    self._handle_websocket_closed()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 221, in _handle_websocket_closed
    feature.close()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 57, in close
    if self.id:
AttributeError: 'GameFeature' object has no attribute 'id'
2022-12-18 02:49:11,160 INFO: [sanic.root] connection open
2022-12-18 02:49:11,160 INFO: [sanic.root] connection open
2022-12-18 02:49:11,160 INFO: [__main__] New websocket client
2022-12-18 02:49:11,161 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:49:11,161 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:49:11,161 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:49:13,224 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:49:13,225 DEBUG: [entrance.ws_handler] WS SEND: {'result': '', 'nfn_type': 'submit_dares', 'channel': 'app', 'id': 1, 'target': 'defaultTarget'}
2022-12-18 02:49:57,994 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:49:57,994 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:49:57,996 INFO: [sanic.root] Server Stopped
2022-12-18 02:49:57,996 INFO: [sanic.root] Server Stopped
2022-12-18 02:49:57,999 INFO: [__main__] Closing down gracefully
2022-12-18 02:49:58,000 INFO: [sanic.server] Stopping worker [7322]
2022-12-18 02:49:58,000 INFO: [sanic.server] Stopping worker [7322]
2022-12-18 02:49:58,000 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:49:58,623 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:49:58,658 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:49:58,658 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:49:58,659 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:49:58,659 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:49:58,714 INFO: [sanic.server] Starting worker [7337]
2022-12-18 02:49:58,714 INFO: [sanic.server] Starting worker [7337]
2022-12-18 02:49:59,035 INFO: [sanic.root] connection open
2022-12-18 02:49:59,035 INFO: [sanic.root] connection open
2022-12-18 02:49:59,037 INFO: [__main__] New websocket client
2022-12-18 02:49:59,037 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:49:59,037 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:49:59,038 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:50:02,929 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:50:02,929 ERROR: [sanic.error] Exception occurred while handling uri: 'ws://localhost:5000/ws'
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/websockets/impl.py", line 538, in recv
    raise asyncio.CancelledError()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 59, in handle_incoming_requests
    req = await asyncio.wait_for(self.ws.recv(), timeout=10*60)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 469, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/app.py", line 1003, in _websocket_handler
    await fut
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 92, in handle_ws
    await ws_handler.handle_incoming_requests()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 70, in handle_incoming_requests
    self._handle_websocket_closed()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 221, in _handle_websocket_closed
    feature.close()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 57, in close
    if self.id:
AttributeError: 'GameFeature' object has no attribute 'id'
2022-12-18 02:50:02,929 ERROR: [sanic.error] Exception occurred while handling uri: 'ws://localhost:5000/ws'
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/websockets/impl.py", line 538, in recv
    raise asyncio.CancelledError()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 59, in handle_incoming_requests
    req = await asyncio.wait_for(self.ws.recv(), timeout=10*60)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 469, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/app.py", line 1003, in _websocket_handler
    await fut
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 92, in handle_ws
    await ws_handler.handle_incoming_requests()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 70, in handle_incoming_requests
    self._handle_websocket_closed()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 221, in _handle_websocket_closed
    feature.close()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 57, in close
    if self.id:
AttributeError: 'GameFeature' object has no attribute 'id'
2022-12-18 02:50:03,260 INFO: [sanic.root] connection open
2022-12-18 02:50:03,260 INFO: [sanic.root] connection open
2022-12-18 02:50:03,261 INFO: [__main__] New websocket client
2022-12-18 02:50:03,261 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:50:03,262 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:50:03,262 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:50:04,964 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:50:04,964 DEBUG: [entrance.ws_handler] WS SEND: {'result': None, 'nfn_type': 'submit_dares', 'channel': 'app', 'id': 1, 'target': 'defaultTarget'}
2022-12-18 02:51:25,807 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:51:25,807 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:51:25,808 INFO: [sanic.root] Server Stopped
2022-12-18 02:51:25,808 INFO: [sanic.root] Server Stopped
2022-12-18 02:51:25,811 INFO: [__main__] Closing down gracefully
2022-12-18 02:51:25,812 INFO: [sanic.server] Stopping worker [7337]
2022-12-18 02:51:25,812 INFO: [sanic.server] Stopping worker [7337]
2022-12-18 02:51:25,813 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:51:26,450 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:51:26,492 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:51:26,492 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:51:26,493 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:51:26,493 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:51:26,564 INFO: [sanic.server] Starting worker [7352]
2022-12-18 02:51:26,564 INFO: [sanic.server] Starting worker [7352]
2022-12-18 02:51:26,869 INFO: [sanic.root] connection open
2022-12-18 02:51:26,869 INFO: [sanic.root] connection open
2022-12-18 02:51:26,869 INFO: [__main__] New websocket client
2022-12-18 02:51:26,870 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:51:26,870 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:51:26,870 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:51:31,546 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:51:31,902 INFO: [sanic.root] connection open
2022-12-18 02:51:31,902 INFO: [sanic.root] connection open
2022-12-18 02:51:31,903 INFO: [__main__] New websocket client
2022-12-18 02:51:31,903 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:51:31,903 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:51:31,903 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:51:35,280 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['s', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:51:35,284 DEBUG: [entrance.ws_handler] WS SEND: {'result': None, 'nfn_type': 'submit_dares', 'channel': 'app', 'id': 1, 'target': 'defaultTarget'}
2022-12-18 02:54:53,793 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:54:53,793 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:54:53,796 INFO: [sanic.root] Server Stopped
2022-12-18 02:54:53,796 INFO: [sanic.root] Server Stopped
2022-12-18 02:54:53,801 INFO: [__main__] Closing down gracefully
2022-12-18 02:54:53,803 INFO: [sanic.server] Stopping worker [7352]
2022-12-18 02:54:53,803 INFO: [sanic.server] Stopping worker [7352]
2022-12-18 02:54:53,804 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:54:54,474 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:54:54,508 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:54:54,508 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:54:54,510 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:54:54,510 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:54:54,562 INFO: [sanic.server] Starting worker [7367]
2022-12-18 02:54:54,562 INFO: [sanic.server] Starting worker [7367]
2022-12-18 02:54:55,106 INFO: [sanic.root] connection open
2022-12-18 02:54:55,106 INFO: [sanic.root] connection open
2022-12-18 02:54:55,107 INFO: [__main__] New websocket client
2022-12-18 02:54:55,107 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:54:55,108 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:54:55,108 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:54:59,313 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:54:59,664 INFO: [sanic.root] connection open
2022-12-18 02:54:59,664 INFO: [sanic.root] connection open
2022-12-18 02:54:59,666 INFO: [__main__] New websocket client
2022-12-18 02:54:59,666 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:54:59,666 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:54:59,667 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:55:05,172 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['an', 'an', 'a', 'n'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:55:05,173 ERROR: [entrance.feature.base] Exception handling submit_dares(, ['an', 'an', 'a', 'n']) (see debug.log for details)
2022-12-18 02:55:05,181 DEBUG: [entrance.feature.base] Exception details
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 93, in handle
    result = await getattr(self, "do_" + req_type)(*args)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 53, in do_submit_dares
    async for player in active_games[code]:
TypeError: 'async for' requires an object with __aiter__ method, got list
Stack (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 152, in <module>
    main(sys.argv[1:])
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 147, in main
    start(config)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 117, in start
    app.run(host=start_cfg["host"], port=start_cfg["port"])
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/mixins/startup.py", line 207, in run
    serve(primary=self)  # type: ignore
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/mixins/startup.py", line 851, in serve
    manager.run()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/manager.py", line 62, in run
    self.start()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/manager.py", line 70, in start
    process.start()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/process.py", line 58, in start
    self._process.start()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/worker/serve.py", line 106, in worker_serve
    return _serve_http_1(
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/runners.py", line 272, in _serve_http_1
    _run_server_forever(
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/sanic/server/runners.py", line 153, in _run_server_forever
    loop.run_forever()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 96, in handle_ws
    await ws_handler.handle_incoming_requests()
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 76, in handle_incoming_requests
    await self._handle_req(req)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 107, in _handle_req
    await feature.handle(request)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 99, in handle
    log.debug("Exception details", exc_info=True, stack_info=True)
2022-12-18 02:55:05,182 DEBUG: [entrance.ws_handler] WS SEND: {'error': "Exception handling submit_dares(, ['an', 'an', 'a', 'n'])", 'nfn_type': 'submit_dares', 'channel': 'app', 'id': 1, 'target': 'defaultTarget'}
2022-12-18 02:57:06,545 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:57:06,545 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:57:06,546 INFO: [sanic.root] Server Stopped
2022-12-18 02:57:06,546 INFO: [sanic.root] Server Stopped
2022-12-18 02:57:06,549 INFO: [__main__] Closing down gracefully
2022-12-18 02:57:06,551 INFO: [sanic.server] Stopping worker [7367]
2022-12-18 02:57:06,551 INFO: [sanic.server] Stopping worker [7367]
2022-12-18 02:57:06,552 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:57:07,149 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:57:07,185 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:57:07,185 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:57:07,186 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:57:07,186 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:57:07,243 INFO: [sanic.server] Starting worker [7382]
2022-12-18 02:57:07,243 INFO: [sanic.server] Starting worker [7382]
2022-12-18 02:57:07,630 INFO: [sanic.root] connection open
2022-12-18 02:57:07,630 INFO: [sanic.root] connection open
2022-12-18 02:57:07,632 INFO: [__main__] New websocket client
2022-12-18 02:57:07,633 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:57:07,633 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:57:07,634 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:57:09,894 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:57:10,244 INFO: [sanic.root] connection open
2022-12-18 02:57:10,244 INFO: [sanic.root] connection open
2022-12-18 02:57:10,245 INFO: [__main__] New websocket client
2022-12-18 02:57:10,245 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:57:10,246 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:57:10,246 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:57:12,552 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['s', 'b', 'b', 'b'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:57:12,559 ERROR: [entrance.feature.base] Exception handling submit_dares(, ['s', 'b', 'b', 'b']) (see debug.log for details)
2022-12-18 02:57:12,561 DEBUG: [entrance.feature.base] Exception details
Traceback (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 93, in handle
    result = await getattr(self, "do_" + req_type)(*args)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 54, in do_submit_dares
    await asyncio.gather(
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/svr/./run.py", line 55, in <genexpr>
    player.collect_dares(dares) for player in active_games[code]
RuntimeError: Task got bad yield: <coroutine object GameFeature.collect_dares at 0x7f20f014cac0>
Stack (most recent call last):
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/ws_handler.py", line 107, in _handle_req
    await feature.handle(request)
  File "/mnt/c/Users/legaul/Documents/personal/dareapp/venv39/lib/python3.9/site-packages/entrance/feature/base.py", line 99, in handle
    log.debug("Exception details", exc_info=True, stack_info=True)
2022-12-18 02:57:12,562 DEBUG: [entrance.ws_handler] WS SEND: {'error': "Exception handling submit_dares(, ['s', 'b', 'b', 'b'])", 'nfn_type': 'submit_dares', 'channel': 'app', 'id': 1, 'target': 'defaultTarget'}
2022-12-18 02:57:58,979 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:57:58,979 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 02:57:58,980 INFO: [sanic.root] Server Stopped
2022-12-18 02:57:58,980 INFO: [sanic.root] Server Stopped
2022-12-18 02:57:58,983 INFO: [__main__] Closing down gracefully
2022-12-18 02:57:58,985 INFO: [sanic.server] Stopping worker [7382]
2022-12-18 02:57:58,985 INFO: [sanic.server] Stopping worker [7382]
2022-12-18 02:57:58,986 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:57:59,608 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 02:57:59,648 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:57:59,648 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 02:57:59,649 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:57:59,649 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 02:57:59,707 INFO: [sanic.server] Starting worker [7397]
2022-12-18 02:57:59,707 INFO: [sanic.server] Starting worker [7397]
2022-12-18 02:58:00,117 INFO: [sanic.root] connection open
2022-12-18 02:58:00,117 INFO: [sanic.root] connection open
2022-12-18 02:58:00,119 INFO: [__main__] New websocket client
2022-12-18 02:58:00,119 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:58:00,120 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:58:00,120 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:58:02,056 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 02:58:02,387 INFO: [sanic.root] connection open
2022-12-18 02:58:02,387 INFO: [sanic.root] connection open
2022-12-18 02:58:02,388 INFO: [__main__] New websocket client
2022-12-18 02:58:02,389 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 02:58:02,389 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 02:58:02,389 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 02:58:06,724 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['s', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 02:58:06,724 DEBUG: [entrance.ws_handler] WS SEND: {'nfn_type': 'collect_dares', 'value': ['s', 'j', 'j', 'j']}
2022-12-18 02:58:06,725 DEBUG: [entrance.ws_handler] WS SEND: {'result': None, 'nfn_type': 'submit_dares', 'channel': 'app', 'id': 1, 'target': 'defaultTarget'}
2022-12-18 03:02:35,386 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 03:02:35,386 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 03:02:35,387 INFO: [sanic.root] Server Stopped
2022-12-18 03:02:35,387 INFO: [sanic.root] Server Stopped
2022-12-18 03:02:35,391 INFO: [__main__] Closing down gracefully
2022-12-18 03:02:35,392 INFO: [sanic.server] Stopping worker [7397]
2022-12-18 03:02:35,392 INFO: [sanic.server] Stopping worker [7397]
2022-12-18 03:02:35,392 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 03:02:36,003 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 03:02:36,039 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 03:02:36,039 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 03:02:36,040 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 03:02:36,040 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 03:02:36,105 INFO: [sanic.server] Starting worker [7412]
2022-12-18 03:02:36,105 INFO: [sanic.server] Starting worker [7412]
2022-12-18 03:02:36,113 INFO: [sanic.root] connection open
2022-12-18 03:02:36,113 INFO: [sanic.root] connection open
2022-12-18 03:02:36,114 INFO: [__main__] New websocket client
2022-12-18 03:02:36,114 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 03:02:36,114 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 03:02:36,115 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 03:02:42,391 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 03:02:42,753 INFO: [sanic.root] connection open
2022-12-18 03:02:42,753 INFO: [sanic.root] connection open
2022-12-18 03:02:42,754 INFO: [__main__] New websocket client
2022-12-18 03:02:42,754 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 03:02:42,754 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 03:02:42,754 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 03:02:45,724 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 03:02:45,725 DEBUG: [entrance.ws_handler] WS SEND: {'nfn_type': 'collect_dares', 'value': ['j', 'j', 'j', 'j'], 'channel': 'app'}
2022-12-18 03:03:52,102 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 03:03:52,102 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 03:03:52,104 INFO: [sanic.root] Server Stopped
2022-12-18 03:03:52,104 INFO: [sanic.root] Server Stopped
2022-12-18 03:03:52,108 INFO: [__main__] Closing down gracefully
2022-12-18 03:03:52,110 INFO: [sanic.server] Stopping worker [7412]
2022-12-18 03:03:52,110 INFO: [sanic.server] Stopping worker [7412]
2022-12-18 03:03:52,111 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 03:03:52,744 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 03:03:52,781 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 03:03:52,781 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 03:03:52,782 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 03:03:52,782 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 03:03:52,841 INFO: [sanic.server] Starting worker [7427]
2022-12-18 03:03:52,841 INFO: [sanic.server] Starting worker [7427]
2022-12-18 03:03:53,125 INFO: [sanic.root] connection open
2022-12-18 03:03:53,125 INFO: [sanic.root] connection open
2022-12-18 03:03:53,126 INFO: [__main__] New websocket client
2022-12-18 03:03:53,127 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 03:03:53,127 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 03:03:53,127 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 03:03:55,969 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 03:03:56,319 INFO: [sanic.root] connection open
2022-12-18 03:03:56,319 INFO: [sanic.root] connection open
2022-12-18 03:03:56,320 INFO: [__main__] New websocket client
2022-12-18 03:03:56,321 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 03:03:56,321 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 03:03:56,321 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 03:03:59,038 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['s', 'n', 'n', 'n'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 03:03:59,039 DEBUG: [entrance.ws_handler] WS SEND: {'nfn_type': 'collect_dares', 'value': ['s', 'n', 'n', 'n'], 'id': 1, 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 03:05:24,933 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 03:05:24,933 INFO: [sanic.root] Received signal SIGINT. Shutting down.
2022-12-18 03:05:24,935 INFO: [sanic.root] Server Stopped
2022-12-18 03:05:24,935 INFO: [sanic.root] Server Stopped
2022-12-18 03:05:24,938 INFO: [__main__] Closing down gracefully
2022-12-18 03:05:24,940 INFO: [sanic.server] Stopping worker [7427]
2022-12-18 03:05:24,940 INFO: [sanic.server] Stopping worker [7427]
2022-12-18 03:05:24,941 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 03:05:25,592 INFO: [__main__] Starting app with host=0.0.0.0, port=5000, static_dir=static
2022-12-18 03:05:25,623 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 03:05:25,623 INFO: [sanic.root] 
  ┌────────────────────────────────────────────────────────────────────────────────┐
  │                                 Sanic v22.9.1                                  │
  │                        Goin' Fast @ http://0.0.0.0:5000                        │
  ├───────────────────────┬────────────────────────────────────────────────────────┤
  │ [48;2;255;13;104m                     [0m │     mode: production, single worker                    │
  │ [38;2;255;255;255;48;2;255;13;104m    ▄███ █████ ██    [0m │   server: sanic, HTTP/1.1                              │
  │ [38;2;255;255;255;48;2;255;13;104m   ██                [0m │   python: 3.9.12                                       │
  │ [38;2;255;255;255;48;2;255;13;104m    ▀███████ ███▄    [0m │ platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glib │
  │ [38;2;255;255;255;48;2;255;13;104m                ██   [0m │           c2.31                                        │
  │ [38;2;255;255;255;48;2;255;13;104m   ████ ████████▀    [0m │ packages: sanic-routing==22.8.0                        │
  │ [48;2;255;13;104m                     [0m │                                                        │
  │ Build Fast. Run Fast. │                                                        │
  └───────────────────────┴────────────────────────────────────────────────────────┘

2022-12-18 03:05:25,624 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 03:05:25,624 WARNING: [sanic.error] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2022-12-18 03:05:25,678 INFO: [sanic.server] Starting worker [7442]
2022-12-18 03:05:25,678 INFO: [sanic.server] Starting worker [7442]
2022-12-18 03:05:26,089 INFO: [sanic.root] connection open
2022-12-18 03:05:26,089 INFO: [sanic.root] connection open
2022-12-18 03:05:26,091 INFO: [__main__] New websocket client
2022-12-18 03:05:26,091 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 03:05:26,092 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 03:05:26,092 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 03:05:28,797 INFO: [entrance.ws_handler] Websocket closed
2022-12-18 03:05:29,133 INFO: [sanic.root] connection open
2022-12-18 03:05:29,133 INFO: [sanic.root] connection open
2022-12-18 03:05:29,134 INFO: [__main__] New websocket client
2022-12-18 03:05:29,135 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 03:05:29,135 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 03:05:29,136 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 03:05:31,294 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['j', 'j', 'j', 'j'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 03:05:31,295 DEBUG: [entrance.ws_handler] WS SEND: {'result': ['j', 'j', 'j', 'j'], 'nfn_type': 'collect_dares', 'id': 1, 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 03:05:42,547 INFO: [sanic.root] connection open
2022-12-18 03:05:42,547 INFO: [sanic.root] connection open
2022-12-18 03:05:42,547 INFO: [__main__] New websocket client
2022-12-18 03:05:42,547 DEBUG: [entrance.ws_handler] Adding configured feature core
2022-12-18 03:05:42,548 DEBUG: [entrance.ws_handler] Skipping unconfigured feature persist
2022-12-18 03:05:42,548 DEBUG: [entrance.ws_handler] Adding configured feature dare_app
2022-12-18 03:05:47,762 DEBUG: [entrance.ws_handler] WS RECV: {'code': '', 'dares': ['h', 'h', 'h', 'h'], 'id': 1, 'req_type': 'submit_dares', 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 03:05:47,763 DEBUG: [entrance.ws_handler] WS SEND: {'result': ['h', 'h', 'h', 'h'], 'nfn_type': 'collect_dares', 'id': 1, 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 03:05:47,763 DEBUG: [entrance.ws_handler] WS SEND: {'result': ['h', 'h', 'h', 'h'], 'nfn_type': 'collect_dares', 'id': 1, 'target': 'defaultTarget', 'channel': 'app', 'userid': 'default'}
2022-12-18 03:06:08,932 INFO: [entrance.ws_handler] Websocket closed
